# Generated by Django 4.1.1 on 2022-09-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoallproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProxy',
        ),
        migrations.CreateModel(
            name='VidePublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Publish video',
                'verbose_name_plural': 'Publish videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
