# Generated by Django 4.1.1 on 2022-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_delete_videoproxy_videpublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Piblish'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
