# Generated by Django 4.1.1 on 2022-09-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
