# Generated by Django 4.1.1 on 2022-09-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categosies', '0001_initial'),
        ('playlists', '0006_movieproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categosies.category'),
        ),
    ]
